### Register User
POST http://localhost:3000/api/auth/register

{
  "username":"rizky",
	"email":"rizky@gmail.com",
	"role":"",
	"password":"123",
	"address":"",
	"phone_number":"",
	"image_url":""
}

### Login User
POST http://localhost:3000/api/auth/login

{
	"email":"azhi@gmail.com",
	"password":"123"
}

### Test Middleware
GET http://localhost:3000/api/auth/test
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpemt5IiwiZW1haWwiOiJyaXpreUBnbWFpbC5jb20iLCJleHAiOjE2OTQ3MTgzMDksImp0aSI6IjUwMzgwOTdjLTFhZWEtNGZhNi04NTM0LWI2MGFlYWMyZWY0YiJ9.QP371nP_Zxn4hZ3NY82dC_pefSV6mSh9rYkK109046Q

### Get Token
GET http://localhost:3000/api/auth/token

### Logout
DELETE http://localhost:3000/api/auth/logout

### Get All Users
GET http://localhost:3000/api/user?page=1&limit=20

### Get User By Id
GET http://localhost:3000/api/user/b1568547-27bc-4d98-a6a6-607a3aad0537

### Update User By Id
PUT http://localhost:3000/api/user/a94ba261-f835-47ba-8f11-8473a67493ce

{
  "username":"Andri Ramdani",
	"email":"andriramdani@gmail.com",
	"password":"",
	"address":"",
	"phone_number":"",
	"image_url":""
}

### Delete User By Id
DELETE http://localhost:3000/api/user/faa2c298-111e-43c0-9b9c-c4559011fb82

### Create Book
POST http://localhost:3000/api/book

{
	"title":"Cita Cita Ku Di NASA",
	"author":"Azhi Muahnaf Rais",
	"publicaion_year":2020,
	"image_url":"",
	"total":50
}

### Get All Books
GET http://localhost:3000/api/book?page=1&limit=3

### Update Book By Id
PUT http://localhost:3000/api/book/edf6d61e-a875-4f0a-a430-5a73bcdd6707

{
	"title":"Mendaki Gunung Rinjani",
	"author":"Rafflyansyah",
	"publicaion_year":0,
	"image_url":"",
	"total":0
}

### Delete Book By Id
DELETE  http://localhost:3000/api/book/edf6d61e-a875-4f0a-a430-5a73bcdd6707

### Get Book By Id
GET  http://localhost:3000/api/book/18ebc3d0-399d-4bff-91a4-f20067c48b85

### BorrowBook
### Must Login
GET  http://localhost:3000/api/book/borrow/18ebc3d0-399d-4bff-91a4-f20067c48b85

### Return Book
### Must Login
GET  http://localhost:3000/api/book/return/18ebc3d0-399d-4bff-91a4-f20067c48b85

### Get All Borrows
GET  http://localhost:3000/api/borrow?page=1&limit=5
