### Register User
POST http://localhost:3000/api/auth/register

{
  "username":"elang",
	"email":"elang@gmail.com",
	"role":"",
	"password":"123",
	"address":"",
	"phone_number":"",
	"image_url":""
}

### Login User
POST http://localhost:3000/api/auth/login

{
	"email":"sandy@gmail.com",
	"password":"123"
}

### Test Middleware
GET http://localhost:3000/api/auth/test
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmR5IiwiZW1haWwiOiJzYW5keUBnbWFpbC5jb20iLCJleHAiOjE2OTQ1NzMyMDIsImp0aSI6ImRiMDM5N2FiLWZiZjEtNDA1NS1iZmE4LTYzOGE3ZDQ3MmEyMyJ9.tfOOaIcZdZqCxH8gCmyc9Jrrud4Nn88ieyRo-nvYyk4
