### Register User
POST http://localhost:3000/api/auth/register

{
  "username":"admin",
	"email":"admin@gmail.com",
	"role":"",
	"password":"admin123",
	"address":"",
	"phone_number":"",
	"image_url":""
}

### Login User
POST http://localhost:3000/api/auth/login

{
	"email":"admin@gmail.com",
	"password":"admin123"
}

### Get Token
### User
GET http://localhost:3000/api/auth/token

### Logout
### User
DELETE http://localhost:3000/api/auth/logout

### Get All Users
### ADMIN
GET http://localhost:3000/api/user?page=1&limit=20
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNDk0MjAsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.Ct7QY6MWH_3YJq-yXv40JGoZVRuD7vWXdANOC-Tob_E

### Get User By Id
### ADMIN
GET http://localhost:3000/api/user/8eb09df1-56da-4927-82df-8d7a4681266b
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTAwNTksImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.gjBcpZ_FL6y4ObFT8oJsjCqetkCjPj1KJf9lb8-jq6I

### Update User By Id
### USER
PUT http://localhost:3000/api/user/8eb09df1-56da-4927-82df-8d7a4681266b
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTMwNjYsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.XsJoT62joa0lqDfKNL2ys6WWIrPeirb_YP4RA1EZBps

{
  "username":"Admin Keren",
	"email":"",
	"password":"",
	"address":"",
	"phone_number":"",
	"image_url":""
}

### Delete User By Id
### USER
DELETE http://localhost:3000/api/user/faa2c298-111e-43c0-9b9c-c4559011fb82
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTM5NTMsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.wW7dAX4uLAkwqDPgpJgtYPgizuav8mWNVW4WKzMA6FQ

### Create Book
### Admin
POST http://localhost:3000/api/book
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIEtlcmVuIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTUwODksImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.-XJP1H_AJTAo3DwffJtdKwVMHwYX5N8yq6I--szX5NE

{
	"title":"Dasar Pemrograman",
	"author":"Admin Keren",
	"publicaion_year":2020,
	"image_url":"",
	"total":50
}

### Get All Books
### User
GET http://localhost:3000/api/book?page=1&limit=3
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIEtlcmVuIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTU2NDUsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.zpQJWuQ_VfjuA0Tj5Lv4mGVucW6ueA_CAtVNnCdV_8E

### Update Book By Id
### Admin
PUT http://localhost:3000/api/book/d4f79719-e5aa-4f9b-b9eb-67ee328aa6bb
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIEtlcmVuIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTYyMzEsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.hhGdPt3feMjV9pRqxtPH7NEVyRR8jMo--TwPypIhO3Q

{
	"title":"Praktek Pemrograman",
	"author":"",
	"publicaion_year":0,
	"image_url":"",
	"total":0
}

### Delete Book By Id
### Admin
DELETE  http://localhost:3000/api/book/edf6d61e-a875-4f0a-a430-5a73bcdd6707
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIEtlcmVuIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTc1NDYsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.DpVKQUmjahbQMwAzKlokHCoqt9B97XZqkPurPxvdnCI

### Get Book By Id
### User
GET  http://localhost:3000/api/book/d4f79719-e5aa-4f9b-b9eb-67ee328aa6bb
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIEtlcmVuIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2OTUwNTc5OTIsImp0aSI6IjhlYjA5ZGYxLTU2ZGEtNDkyNy04MmRmLThkN2E0NjgxMjY2YiJ9.zKyKQMOKrlZGrVASNoPZeUeeX-G917mkmkHj0ZZsxf8

### BorrowBook
### User Must Login
GET  http://localhost:3000/api/book/borrow/18ebc3d0-399d-4bff-91a4-f20067c48b85
Access-Token:

### Return Book
### User Must Login
GET  http://localhost:3000/api/book/return/18ebc3d0-399d-4bff-91a4-f20067c48b85
Access-Token:

### Get All Expired
### Admin
GET  http://localhost:3000/api/book/expired?page=1&limit=5
Access-Token: